#!/bin/bash
# /etc/init.d/fancontroler
  
### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: CPU fan control
# Description: This service is used to control cpu fan.
### END INIT INFO
  
case "$1" in
    start)
        echo "Starting Fancontroler"
        sudo autocontrolfan &
        ;;
    stop)
        echo "Stopping Fancontroler"
        kill $(ps aux | grep -m 1 'sudo autocontrolfan' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service fancontroler start|stop"
        exit 1
        ;;
esac
exit 0
